"""The 39 upstream acceptance-case IDs, case-level obligations and candidate test witnesses.

Expected outcomes are a reviewer-friendly transcription of the official cases, NOT a copy of
semantic_cases.json. The official manifest must be loaded separately from its pinned blob
before issuing an upstream-conformance certificate.

Each witness points at an actual unittest method in earlier research modules. These
are partial witnesses, not in themselves the complete acceptance trace.
"""
from dataclasses import dataclass

@dataclass(frozen=True)
class Case:
    id: str
    expectation: str
    witnesses: tuple[str,...]
    missing: tuple[str,...]
    profile: str='ALL'

# All tests refer to the actual method name (without the 'test_' prefix); the runner
# disambiguates with the module hint before executing. The missing obligations are
# explicit, and MUST NOT be silently dropped after a test passes.
CASES=[
Case('CORE-01','Full valid signed chain, exactly one ACCEPTED and immutable COMMIT/Ref',('phase8:all_five_fixed_synthetic_paths','phase4:acceptance_record_contract_exact'),('verified original normative records for all profiles','full current typed dependency graph','all Result and response bindings')),
Case('CORE-02','Reject tampered body/profile/scope/audience/path without acceptance or dispatch',('reference_executor:envelope_reject_cross_profile','phase8:evidence_kind_cannot_be_cross_profile_reused','phase8:broken_signed_permit_rejected'),('HTTP route and audience matrix across all profiles','all message types and side-effect assertions')),
Case('CORE-03','Reject validly re-signed Permit with omitted mandatory Dep',('phase4:signature_valid_missing_permit_dep_rejected','strict_v26:resigned_permit_missing_dependency_rejected'),('complete independent RequiredDeps closure for IND/MED','complete certified control and transitive issuer graph')),
Case('CORE-04','Reject conflicting same-key Dep, wrong record kind, and cycles',('strict_v26:duplicate_same_key_rejected','strict_v26:wrong_record_kind_rejected'),('cyclic reference graph rejection at full depth','typed Record/Envelope recursive graph with limits')),
Case('CORE-05','Reject stale range/empty-set revisions, revision rollback, ABA',('assurance:empty_range_to_nonempty_changes_revision','strict_v26:reactivate_old_content_does_not_revive_old_ref','phase8:controller_update_invalidates_signed_candidate'),('W protected range insert/delete and ABA in same transaction','all three profile ranges and historical epochs')),
Case('CORE-06','Distinguish authorized temporarily unavailable U from known missing F',('phase8:source_current_row_disappears_fail_closed','strict_v26:missing_role_row_cannot_be_filled_by_client'),('authenticated temporarily unavailable service case, U/DEFER','independent missing-object F/REJECT signed Result and zero effects')),
Case('CORE-07','Issuer cannot replace U; required reviewers independent by subject and purpose',('strict_v26:independent_finance_not_gateway','strict_v26:independent_review_not_finance','phase8:wrong_review_purpose_rejected'),('same subject different kid role collision full-envelope case','all three profile signature authority matrix')),
Case('CORE-08','Pre-commit failure rolls back; ambiguous commit cannot be called DEFER',('phase5:true_process_hard_kills_at_commit_boundaries','phase8:hard_crash_rolls_back_every_write'),('client ambiguous communication outcome protocol semantics','complete W all-record transactional snapshot')),
Case('CORE-09','Post-commit signing failure recovers original Core/Ref even revoked signing key',('phase5:signed_commit_persists_and_recovers_new_connection','phase4:acceptance_record_contract_exact'),('inject actual post-commit signer failure and key-revocation recovery','restore archived original signing key witness and immutable bytes')),
Case('CORE-10','Damaged archive signature or substituted signed Core cannot be returned',('phase5:archive_tamper_rejected','phase4:archive_commit_mutation_detected','phase4:wrong_acceptance_signature_detected'),('validly re-signed different historical Core challenge','full archived credential chain identity and certificate witness')),
Case('CORE-11','Same proof/nonce returns original; changed proof replay; different action intent conflict',('phase5:replay_same_bytes_returns_original_receipt_without_new_accept','phase5:same_operation_changed_signed_proof_rejects','phase8:nonce_same_other_proof_rejected'),('nonce and proof side-effect trace from full multi-profile W','issue/request ID idempotency and all distinct action variants')),
Case('CORE-12','Eight parallel submissions share one acceptance and satisfy capacity constraint',('phase5:eight_thread_duplicate_submission_one_accept','phase8:eight_concurrent_identical_submit_single_accept'),('eight distinct candidates racing shared resource','multi-process capacity and same-intent concurrency for all profiles')),
Case('CORE-13','Pre-dispatch revoked/expired/cross-boundary evidence does not execute',('phase7:policy_revocation_before_claim_blocks','phase7:aba_revision_change_even_same_ref_blocks','phase8:role_revocation_after_accept_blocks_dispatch'),('merge legacy and guarded dispatch implementations; legacy revocation gap exists','authoritative trusted-time interval crossing and deterministic cancellation')),
Case('CORE-14','Allow own behavior change, reject lost reservation/flight with HALTED',('phase4:dispatch_allows_only_acceptance_own_behavior_change','phase4:reservation_ownership_violation_blocks_claim','phase8:behavior_inflight_missing_blocks_dispatch'),('transactionally prove HALTED without partial release for all corruptions','interleaved legitimate behavior revisions with nondecreasing count')),
Case('CORE-15','Pending cancellation/claim race; started fault unknown and never redispatch',('phase6:claim_is_one_shot_no_arbitrary_witness_bool','phase5:claim_single_dispatch_and_restart_unknown','reference_executor:cancel_only_before_start'),('true concurrent cancel-versus-claim interleaving','tool no-late-effect callback contract after crash')),
Case('CORE-16','Tool outcome trust and binding, duplicate idempotence, true conflict HALTED',('phase6:bad_signature_cannot_halt','phase6:trusted_conflicting_fact_halts_without_reverse_settlement','phase6:binding_wrong_attempt_rejected_unchanged'),('full cross-profile integrated final ledger','signatures and registered external ledger continuity')),
Case('CORE-17','STATUS with current holder new kid reads old accepted record only',('phase4:status_query_read_only','reference_executor:status_after_old_challenge_expiry'),('real holder key migration and current STATUS challenge','signed Result and old COMMIT proof across expiry')),
Case('CORE-18','Stable intent prevents v2.5/v2.6 duplicate acceptance and after terminal state',('phase5:same_intent_different_operation_conflict','assurance:stable_intent_blocks_second_candidate'),('v2.5 persisted intent migration to v2.6','tombstones retained after settled/cancelled operations')),
Case('CORE-19','Enrollment key-possession proof binding/nonce/root/purpose',('conformance39:exact_possession_registers_one_key_no_business_role','conformance39:modified_scope_rejected','conformance39:modified_purposes_rejected','conformance39:modified_root_rejected','conformance39:wrong_nonce_rejected','conformance39:root_rotation_blocks_unconsumed_proof','conformance39:nonce_proof_replacement_after_first_accept_rejected'),('remote C controller identity service and trusted nonce issuance not implemented','original governance audit and role issuance lifecycle not integrated')),
Case('CORE-20','G/X service kid bound to current POLICY; key rotation invalidates old',('strict_v26:gateway_kid_fixed_to_policy','phase8:key_revocation_prevents_accept'),('both issuer and executor multi-key same-subject cases','service rotation reissue Policy and all downstream receipts')),
Case('PAY-01','CLEAR/FLAG/INSUFFICIENT review purpose and FINANCE authorization',('phase4:pay_clear_full_signed_acceptance','phase4:pay_flag_requires_anomaly_review','phase4:pay_insufficient_requires_low_evidence_review'),('official full current issuer/source identity and RoleGrant graph','complete three traces in official transport wrapper'), 'PAY-1'),
Case('PAY-02','n=2, n=5 d=4, distance=1000, event/known cutoff and selection order',('strict_v26:n2_insufficient','strict_v26:n5_d4_flag','strict_v26:distance_equal_1000_included','strict_v26:time_known_at_at_cutoff_included','strict_v26:time_known_at_after_cutoff_excluded','strict_v26:order_by_distance_then_ascii_case_id'),('original authenticated History publication audit and trusted cutoff origin','full official-case transcript with all negative variants'), 'PAY-1'),
Case('PAY-03','Reject duplicate case_id/intent, forged client cutoff or risk result',('strict_v26:duplicate_case_id_reject_before_filter','strict_v26:duplicate_intent_reject_before_filter','strict_v26:claimed_cutoff_tamper_rejected','strict_v26:unsigned_claimed_clear_rejected_on_flag'),('full execution under C-authenticated case snapshot and real signer','same source row verified at W acceptance'), 'PAY-1'),
Case('PAY-04','Known false order acceptance/unsettled/payee or changed amount hard F',('strict_v26:known_false_hard_reject','strict_v26:amount_over_cap','strict_v26:payee_outside_allowlist'),('all three Boolean hard-false variations','complete signed Result and read-only resource ledger'), 'PAY-1'),
Case('PAY-05','Legacy Evidence whitelist, preserved v2.5 sig, and current role',('strict_v26:wrong_source_version_rejected','strict_v26:v25_signature_tamper_even_with_recomputed_ref','strict_v26:wrong_source_ref_rejected'),('original v2.5 issuer credential publication chain and migration witness','all rejected source types and removed-original-sig cases'), 'PAY-1'),
Case('IND-01','Three synthetic labels fixed routes, uncertain requires quality review',('phase8:all_five_fixed_synthetic_paths','phase8:ind_defect_cannot_release','phase8:missing_required_review_rejected'),('full original IND Schema and controller key PoP','every profile role scope/reader and full source lineage'),'IND-DEMO-1'),
Case('IND-02','Reject policy-bound detector/preprocessing/mapper mixup',('phase8:ind_fixed_package_mismatch_is_rejected','phase8:ind_missing_package_fails_closed'),('all independent package-dimension mismatches under authoritative C publication','official IND structural Schema validation'),'IND-DEMO-1'),
Case('IND-03','Accept self scene transition, reject external evidence update before dispatch',('phase8:scene_external_update_after_accept_blocks_dispatch','phase8:commit_contains_full_scene_and_resource_witnesses'),('separate source revisions and external evidence updates','full atomic W scene-after witness and authentic dispatch claim'),'IND-DEMO-1'),
Case('IND-04','Cycle1 INSPECT successful advance; cycle2 INSPECT hold; unknown cannot advance',('conformance39:unknown_attempt_cannot_advance','conformance39:cycle_one_signed_success_allows_exactly_one_advance','conformance39:cycle_two_inspect_success_goes_to_manual_hold','conformance39:bad_tool_signature_cannot_advance_or_release'),('controller privilege is an in-process lab assumption rather than authenticated C certificate','R2 FinalFact signer is lab-pinned rather than certified external TOOL_TRUST + independent ledger'),'IND-DEMO-1'),
Case('MED-01','Clinical review and independent medical authorization always required',('phase8:all_five_fixed_synthetic_paths','phase8:wrong_review_purpose_rejected','phase8:review_read_permission_revocation'),('two same-subject/different-kid medical approvers','full med read authorizer and fixed role scope'),'MED-DEMO-1'),
Case('MED-02','Exact patient/encounter/template/evidence binding; no new group bypass',('phase8:med_wrong_patient_rejected','phase8:med_wrong_group_rejected','phase8:med_wrong_record_ref_rejected','phase8:med_wrong_template_rejected'),('attempt re-register group after prior final','official MED Schema and verified unique encounter lifecycle'),'MED-DEMO-1'),
Case('MED-03','Known UNAVAILABLE/INCOMPLETE F distinct from unknown source U',('phase8:med_signed_but_unavailable_record_is_hard_reject','phase8:med_signed_but_incomplete_record_is_hard_reject'),('authorized temporarily unavailable E authority U path','F/U reason signed Result and W noneffects'),'MED-DEMO-1'),
Case('MED-04','Reader grants enforced before access; auditor redaction; revoked read invalidates',('phase8:read_permission_missing_blocks_preparation','phase8:review_read_permission_revocation'),('auditor cannot expose patient detail; redaction fields test','full authenticated reader identities and revocation race'),'MED-DEMO-1'),
Case('SC-01','300 second trust interval, 8 resource slots, 32 accepted cap',('phase8:source_expires_at_upper_boundary','phase8:zero_capacity_rejects_without_consuming'),('exact 8-slot full-capacity test and 32-operation cumulative behavior test','trusted lo/hi 300-second T/F/U semantics'),'IND-DEMO-1,MED-DEMO-1'),
Case('SC-02','Cross-Profile signature, records, task, permit, HTTP path rejected',('phase8:evidence_kind_cannot_be_cross_profile_reused','phase8:ind_med_receipts_have_different_protected_profiles','reference_executor:cross_profile_tool_final_rejected'),('cross-profile signed CORE envelopes and path','official structures and W noneffects for each direction')),
Case('AUD-02A','Expired first tool final, current same-fact reattestation settles once',('phase6:expired_first_proof_requires_fresh_reattest','phase6:two_crash_boundaries_recovery'),('integrated R2 final into IND/MED W','audited C ledger mapping and tool real authorization')),
Case('AUD-02B','Tool key rotation; new RecordRef same FinalFactID settles once',('phase6:rotation_recovery_same_ledger','phase6:same_fact_fresh_attestation_new_ref_no_second_settlement'),('controller rollover evidence, verified registered ledger continuity','integrated all three profiles')),
Case('AUD-02C','Lost tool ledger or new ledger cannot falsely settle old attempt',('phase6:missing_fact_never_implies_failed','phase6:rotation_to_different_ledger_reject','phase6:same_ledger_id_separate_storage_origin_rejected'),('actual external tool ledger unavailable/rollback semantics','independent status and resource ownership across restart')),
Case('AUD-02D','Bad signature / wrong binding cannot halt; authenticated contradiction HALTED',('phase6:bad_signature_cannot_halt','phase6:trusted_conflicting_fact_halts_without_reverse_settlement','phase6:binding_wrong_attempt_rejected_unchanged'),('all profiles and actual tool trust lineage','full response and escrow log in HALTED')),
]
EXPECTED_IDS=('CORE-01 CORE-02 CORE-03 CORE-04 CORE-05 CORE-06 CORE-07 CORE-08 CORE-09 CORE-10 CORE-11 CORE-12 CORE-13 CORE-14 CORE-15 CORE-16 CORE-17 CORE-18 CORE-19 CORE-20 PAY-01 PAY-02 PAY-03 PAY-04 PAY-05 IND-01 IND-02 IND-03 IND-04 MED-01 MED-02 MED-03 MED-04 SC-01 SC-02 AUD-02A AUD-02B AUD-02C AUD-02D').split()
assert [c.id for c in CASES]==EXPECTED_IDS and len(CASES)==39
